save_dir: './nvas3d/assets/saved_models'
use_visual: False
use_deconv: True

data_loader:  
  batch_size: 96
  num_workers: 8
  num_receivers: 4
  hop_length: 480
  win_length: 1200
  n_fft: 2048
  nvas3d_dataset: 'nvas3d_square_all_all'
  audio_format: 'flac'
  
training:
  epochs: 200
  lr: 0.001
  weight_decay: 0.0
  detect_loss_weight: 0.1
  save_checkpoint_interval: 10
  resume: False
  checkpoint_dir: None
  

  
